name: TestScan

on:
  push:
    branches:
      - main

jobs:
  Scan:
    runs-on: ubuntu-latest
    
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Use Node.js '16.17.1'
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.1'
        cache: 'npm'
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Update npm
      run: npm install -g npm && npm --version
    - name: Install dependencies
      run: npm ci
    - name: Copy env
      run: cp .env.example .env
    - name: Test
      run: npm test 
    - name: Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
